In [1]:
import numpy as np

In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9])
s=np.array_split(arr,3)
for i in s[0]:
    i+=1
    print(i)
    



2
3
4


array([1, 2, 3])

In [25]:
arr=np.array([[1,2,3],[3,4,6]])
s=np.array_split(arr,3,axis=1)
s

[array([[1],
        [3]]),
 array([[2],
        [4]]),
 array([[3],
        [6]])]

## searching in np


In [35]:
arr=np.array([8,9,5,3,2,1])
s=np.where(arr>3)
a=np.where(arr==3)
print(s)
print(a)

# for checking which element is divisible by 2 , gives the remainder 0
sr=np.where(arr%2==0)
print(sr)



(array([0, 1, 2], dtype=int64),)
(array([3], dtype=int64),)
(array([0, 4], dtype=int64),)


In [36]:
# if you have  a sorted aray and you want to check the element index
arr=np.array([3,4,5,7,8,9,11])
search_sorted=np.searchsorted(arr,7)
print(search_sorted)

3


## filter

In [38]:
arr=np.array([3,4,5,7,8])
fa=[True,False,True,False,False]
new=arr[fa]
# now the new list is containing only the true elements (matching )

print(new)

[3 5]


In [42]:
arr=np.array([3,4,5,7,8,9,13,45,66,12,21,28,33,44,55,66,11])
fa=arr%2==0
new=arr[fa]
print(new)
new=np.sort(new)
print('this is a sorted :',new)

# contains only even nubers 

[ 4  8 66 12 28 44 66]
this is a sorted : [ 4  8 12 28 44 66 66]


In [43]:
arr=np.array([3,4,5,7,8,9,13,45,66,12,21,28,33,44,55,66,11])
fa=arr>13
new=arr[fa]
print(new)


[45 66 21 28 33 44 55 66]


## random shuffle unique resize and ravel

In [46]:
arr=np.array([3,4,5,7,8,9,13,45,66,12,21,28,33,44,55,66,11])
print(arr)
np.random.shuffle(arr)
print(arr)

[ 3  4  5  7  8  9 13 45 66 12 21 28 33 44 55 66 11]
[44 11  3 33 13  8  5 45  4 28 12  7 66 55 21  9 66]


In [47]:
arr=np.array([3,4,5,7,8,9,13,45,66,12,21,28,33,44,55,66,11])
#  i want only unique elements 

new=np.unique(arr)
print(new)

[ 3  4  5  7  8  9 11 12 13 21 28 33 44 45 55 66]


In [50]:
arr=np.array([3,4,5,7,8,9,13,45,66,12,21,28,33,44,55,66,11])

print(np.resize(arr,(5,4)))

[[ 3  4  5  7]
 [ 8  9 13 45]
 [66 12 21 28]
 [33 44 55 66]
 [11  3  4  5]]


In [51]:
# ravel function flatten our arrays irrespective of its dimensions
arr=np.array([[[3,4,5],[7,8,9],[13,45,66]]])

print(np.ravel(arr))



[ 3  4  5  7  8  9 13 45 66]


In [52]:
arr=np.array([3,4,5,6])
print(arr)

print(np.insert(arr,(1,2,4),50))


[3 4 5 6]
[ 3 50  4 50  5  6 50]


In [57]:
arr=np.array([[20,40],[60,80]])
print(arr)

print(np.insert(arr,1,50,axis=0))
print(np.insert(arr,1,50,axis=1))

[[20 40]
 [60 80]]
[[20 40]
 [50 50]
 [60 80]]
[[20 50 40]
 [60 50 80]]


In [58]:
arr=np.array([[20,40],[60,80]])
print(arr)

print(np.insert(arr,1,[50,40],axis=0))

[[20 40]
 [60 80]]
[[20 40]
 [50 40]
 [60 80]]


In [59]:
# deletion

arr=np.array([3,4,5,6,11,34,23])
print(arr)
print(np.delete(arr,4))

[ 3  4  5  6 11 34 23]
[ 3  4  5  6 34 23]


In [65]:
arr=np.array([[20,40],[60,80]])
print(np.delete(arr,1,axis=1))

[[20]
 [60]]


## Arthematic operations

In [87]:
arr1=np.array([3,4,5,6,11,34,23])
arr2=np.arange(11,18,1)
print(arr1+arr2)
print(arr2-arr1)
print(arr2*arr1)
print(np.round((arr2/arr1),2))

print(arr2%arr1)
print(arr1**arr2)

[14 16 18 20 26 50 40]
[  8   8   8   8   4 -18  -6]
[ 33  48  65  84 165 544 391]
[3.67 3.   2.6  2.33 1.36 0.47 0.74]
[ 2  0  3  2  4 16 17]
[    177147   16777216 1220703125 1054752768 1632031715 2030108672
 -285245545]


In [98]:
arr1=np.array([[-2,3],[4,5]])
arr2=np.array([[1,-2],[3,2]])

print(arr1*arr2)

[[-2 -6]
 [12 10]]


In [102]:
# built in arthematic functions

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.mod(arr1,arr2))



print(np.divmod(arr1,arr2))

print(f'this is a absolute')
print(np.absolute(arr2))

# floor_divide gives the queotent


print(np.floor_divide(arr1,arr2))



[[ 0  6]
 [ 8 10]]
[[-4  0]
 [ 0  0]]
[[-4  9]
 [16 25]]
[[-1.  1.]
 [ 1.  1.]]
[[0 0]
 [0 0]]
(array([[-1,  1],
       [ 1,  1]]), array([[0, 0],
       [0, 0]]))
this is a absolute
[[2 3]
 [4 5]]
[[-1  1]
 [ 1  1]]


## matrix in np

In [104]:
mat1=np.matrix([[-2,3],[4,5]])
mat2=np.matrix([[1,-2],[3,2]])

print(np.dot(mat1,mat2))
print(np.cross(mat1,mat2))

[[ 7 10]
 [19  2]]
[ 1 -7]


In [107]:
# transpose
mat2=np.matrix([[1,-2],[3,2]])
print(mat2.transpose())
print(mat2.T)

[[ 1  3]
 [-2  2]]
[[ 1  3]
 [-2  2]]


In [109]:
a,b,c=10,20,30

In [113]:
a=10
b=10
c=11
print(type(a))
print(id(a))
print(id(b))
print(id(c))

<class 'int'>
140729535023832
140729535023832
140729535023864
