In [1]:
import numpy as np

## 1. Write a NumPy program to find the dot product of two arrays of different dimensions.
  

In [2]:
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([1,2,3])

ans=np.dot(arr1,arr2)
print(ans)

[14 26]


In [8]:
## Stack a 3x3 identity matrix vertically and horizontally

matrix=np.identity(3)
print(matrix)

v=np.vstack((matrix,matrix,matrix))
h=np.hstack((matrix,matrix,matrix))
print('this is verticle\n',v)
print('this is horizental\n ',h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
this is verticle
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
this is horizental
  [[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


In [15]:

# 3
arr3 = np.random.randint(50, size=(4,4))

print(arr3)

print(np.sum(arr3,axis=1))

[[34 10 37 14]
 [13 38 12 39]
 [ 2 12 20 31]
 [19 40 10 17]]
[ 95 102  65  86]


In [20]:
#4  
arr4=np.random.randint(21,size=(3,3))
m=np.mean(arr4,axis=1)
print(m)
print(" Now mean is subtracted from every element" )
print(np.subtract(arr4,m))

[11.         13.33333333 11.33333333]
 Now mean is subtracted from every element
[[-1.         -2.33333333  0.66666667]
 [ 5.          0.66666667 -1.33333333]
 [ 3.          2.66666667 -7.33333333]]


In [29]:
from numpy import subtract


arr4=np.random.randint(21,size=(3,3))
m=np.mean(arr4,axis=0)
print(m)
print(" Now mean is subtracted from every column element" )
print((np.round(subtract(arr4,m),3)))

[10.         11.33333333 16.        ]
 Now mean is subtracted from every column element
[[-5.    -3.333 -5.   ]
 [ 2.    -2.333  3.   ]
 [ 3.     5.667  2.   ]]


In [30]:
arr6=np.random.randint(21,size=(5,5))


print(" this is a original array and" )
print(arr6)
print(' this is a normalixed')
print(np.subtract(arr6,np.mean(arr6,axis=1,keepdims=True)))



 this is a original array and
[[ 8  7 11  2  4]
 [ 0 16 13  2 10]
 [10 18 12 16 14]
 [20 10  4  7  7]
 [ 2  0  9 10 11]]
 this is a normalixed
[[ 1.6  0.6  4.6 -4.4 -2.4]
 [-8.2  7.8  4.8 -6.2  1.8]
 [-4.   4.  -2.   2.   0. ]
 [10.4  0.4 -5.6 -2.6 -2.6]
 [-4.4 -6.4  2.6  3.6  4.6]]


In [28]:
arr7=np.random.randint(21,size=(5,5))


print(" this is a original array and" )
print(arr7)
print(' this is a normalixed')
print(np.subtract(arr7,np.mean(arr7,axis=0,keepdims=True)))

 this is a original array and
[[15  6  5 14  7]
 [ 2 17  2 19  6]
 [ 2 12 18 19 16]
 [ 5  7  9 10 20]
 [16 16 12 10  1]]
 this is a normalixed
[[ 7.  -5.6 -4.2 -0.4 -3. ]
 [-6.   5.4 -7.2  4.6 -4. ]
 [-6.   0.4  8.8  4.6  6. ]
 [-3.  -4.6 -0.2 -4.4 10. ]
 [ 8.   4.4  2.8 -4.4 -9. ]]


In [48]:
from numpy import where


arr7=np.random.randint(21,size=(5,5))

print('this is a original array\n',arr7)
print('this is  a desired result')
s=np.sort(arr7,axis=1)
print(s[:,-2])

 

this is a original array
 [[ 5 16 12 11 13]
 [17  9  2 18 20]
 [ 8  6  3 15  4]
 [ 9 13 19  8  2]
 [ 5 12  3 20 19]]
this is  a desired result
[13 18  8 13 19]


In [54]:
arr7=np.random.randint(21,size=(5,5))
print('this is original\n',arr7)
zero=np.zeros((3,3))
print(arr7[1:(1)])

this is original
 [[ 2 18 13  6  0]
 [ 1  1 16  7 15]
 [ 5 16  4  1  4]
 [13 20 11 16  0]
 [12 16  2 11  1]]
[]


Original Array:
[[ 2 18 13  6  0]
 [ 1  1 16  7 15]
 [ 5 16  4  1  4]
 [13 20 11 16  0]
 [12 16  2 11  1]]

New Array:
[[ 2 18 13  6  0]
 [ 1  1 16  7 15]
 [ 5 16  0  1  0]
 [13 20 11 16  0]
 [12 16  2 11  1]]
