In [1]:
import numpy as np

In [4]:
arr=np.arange(1,6,dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [10]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [16]:
print(np.zeros((3,3),dtype=int))
# default dtype is float

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
print(np.ones((3,3),dtype=int))
print('this is a 1 dim ar')
print(np.ones(3))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
this is a 1 dim ar
[1. 1. 1.]


In [25]:
print(np.full(8,7))
print(np.full((3,4),99,dtype=float))

[7 7 7 7 7 7 7 7]
[[99. 99. 99. 99.]
 [99. 99. 99. 99.]
 [99. 99. 99. 99.]]


In [36]:
print(np.arange(32).reshape(4,1,8))

[[[ 0  1  2  3  4  5  6  7]]

 [[ 8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]]]


In [51]:
print(np.arange(9).reshape(1,3,3))

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


# functions of numpy


In [62]:
arr=np.repeat([3.4],5,axis=0)
print(arr)

[3.4 3.4 3.4 3.4 3.4]


In [68]:
arr=np.repeat([[3,7]],5,axis=0)
print(arr)

[[3 7]
 [3 7]
 [3 7]
 [3 7]
 [3 7]]


In [78]:
from numpy import concatenate


arr=np.array([[1,4,56,6],[1,2,49,51]])
arr1=np.array([[4,5,6,7]])

concatenate((arr,arr1),axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1