In [2]:
import numpy as np

In [128]:
arr=np.arange(1,6,dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [129]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [130]:
print(np.zeros((3,3),dtype=int))
# default dtype is float

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [131]:
print(np.ones((3,3),dtype=int))
print('this is a 1 dim ar')
print(np.ones(3))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
this is a 1 dim ar
[1. 1. 1.]


In [132]:
print(np.full(8,7))
print(np.full((3,4),99,dtype=float))

[7 7 7 7 7 7 7 7]
[[99. 99. 99. 99.]
 [99. 99. 99. 99.]
 [99. 99. 99. 99.]]


In [133]:
print(np.arange(32).reshape(4,1,8))

[[[ 0  1  2  3  4  5  6  7]]

 [[ 8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]]]


In [134]:
print(np.arange(9).reshape(1,3,3))

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


# functions of numpy


In [135]:
arr=np.repeat([3.4],5,axis=0)
print(arr)

[3.4 3.4 3.4 3.4 3.4]


In [136]:
arr=np.repeat([[3,7]],5,axis=0)
print(arr)

[[3 7]
 [3 7]
 [3 7]
 [3 7]
 [3 7]]


In [137]:
from numpy import concatenate


arr=np.array([[1,4,5,6],[1,4,5,9]])
arr1=np.array([[4,5,6,7],[2,5,7,8]])

concatenate((arr,arr1),axis=1)

array([[1, 4, 5, 6, 4, 5, 6, 7],
       [1, 4, 5, 9, 2, 5, 7, 8]])

## using vstack


In [138]:
v=np.vstack((arr,arr1))
v

array([[1, 4, 5, 6],
       [1, 4, 5, 9],
       [4, 5, 6, 7],
       [2, 5, 7, 8]])

In [139]:
h=np.hstack((arr,arr1))
h

array([[1, 4, 5, 6, 4, 5, 6, 7],
       [1, 4, 5, 9, 2, 5, 7, 8]])

In [140]:
arr=np.array([x for x in range(7)])
p=np.power(arr,2)
print(p)

# for different powers for each element in arr 
p2=np.power(arr,[x for x in range(7)])
p2

[ 0  1  4  9 16 25 36]


array([    1,     1,     4,    27,   256,  3125, 46656])

## difference

In [141]:
from ctypes import sizeof


arr=np.array(range(9,18))
arr1=np.array(range(20,29))

d=np.diff((arr,arr1),axis=0)
print(d)

[[11 11 11 11 11 11 11 11 11]]


## cross 

In [142]:
arr=np.array([1,5])
arr1=np.array([2,7])
c=np.cross(arr,arr1)
print(c)

-3


### sort


In [143]:
arr=np.array([1,5,6,4])
arr1=np.array([2,7,3,6])
s=np.sort((arr,arr1),axis=0)
print(s)

# elements from both arrays compare and what is smaller comes 
# whether it is from 1st or 2nd arr 

[[1 5 3 4]
 [2 7 6 6]]


In [144]:
arr=np.array([1,5,6,4])
arr1=np.array([2,7,3,6])
s=np.sort((arr,arr1),axis=1)
print(s)

# now elements are compare in same list and get sorted

[[1 4 5 6]
 [2 3 6 7]]


## flatten

In [149]:
n1=[2,3,8,5]
n2=[4,3,1,9]

n=np.array([n1,n2])
print(n.flatten("C"))

[2 3 8 5 4 3 1 9]


In [150]:
print(n.sum(axis=0))

[ 6  6  9 14]


In [147]:
import numpy as np

a = np.array([1.0, 2.0, np.nan, 4.0])

# Performing operations with NaN
b = a + 5

print(b)


[ 6.  7. nan  9.]


In [157]:
print(np.cumsum(n,axis=0))
# now cumprod
print(np.cumprod(n))
# if a axis is default then it will flatten 
# the array multiply each element by its previous


# now using the axis
print(np.cumprod(n,axis=0))

[[ 2  3  8  5]
 [ 6  6  9 14]]
[    2     6    48   240   960  2880  2880 25920]
[[ 2  3  8  5]
 [ 8  9  8 45]]


## ietration in np 


In [158]:
arr=np.array([1,2,3,4,6,7,9])

for i in arr:
    print(i)

1
2
3
4
6
7
9


In [160]:
arr=np.array([[1,2,3,4,6,7,9],[5,1,3,6,9,7,3]])

for i in arr:
    for j in i:

        print(j)

1
2
3
4
6
7
9
5
1
3
6
9
7
3


In [164]:
# 3d array 

arr3=np.array([[[1,2],[3,8]],[[5,1],[8,12]]])
# for i in arr3:
#     for j in i:
#         for k in j:
#             print(k)

# this is not optimal

for i in np.nditer(arr3):
    print(i)


1
2
3
8
5
1
8
12


In [165]:
# np also has enumerate 

# 3d array 

arr3=np.array([[[1,2],[3,8]],[[5,1],[8,12]]])


for ind,ele in np.ndenumerate(arr3):
    print(ind,ele)


(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 8
(1, 0, 0) 5
(1, 0, 1) 1
(1, 1, 0) 8
(1, 1, 1) 12


## copy vs view function

In [167]:
arr=np.array([1,2,3,4,6,7,9])
c=np.copy(arr)
arr[2]=7
print('original :',arr)
print('copy :',c)


original : [1 2 7 4 6 7 9]
copy : [1 2 3 4 6 7 9]


In [169]:
# view 
arr=np.array([1,2,3,4,6,7,9])
v=arr.view()
arr[3]=7
print('original :',arr)
print('view copy :',v)

original : [1 2 3 7 6 7 9]
view copy : [1 2 3 7 6 7 9]


In [172]:
a=np.array([1,2])
# a=np.append(a,3)
a=np.append(a,[3,4.0])
print(a)
# all converts to float

[1. 2. 3. 4.]


## insertion in np

In [176]:
a = np.array([1.0, 2.0, 3.0])
a=np.insert(a,1,values=3.5)
a

array([1. , 3.5, 2. , 3. ])

In [177]:
a = np.insert(a, 2, values=[100, 200])
a

array([  1. ,   3.5, 100. , 200. ,   2. ,   3. ])

In [180]:
# Insert multiple elements at multiple positions
a = np.insert(a, [3, 5], values=[4.2, 5.2])
a


array([  1. ,   3.5, 100. ,   4.2,   4.5,   4.5,   5.2, 200. ,   5.5,
         2. ,   5.5,   3. ])

## deleting a element

In [185]:
a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
a = np.delete(a, -1)
print(a)

[1. 2. 3. 4.]


In [186]:
a = np.delete(a, [0, 1])
a
# a is now [3., 4.]

array([3., 4.])

In [188]:
a = np.array([1.0, 3.0, 2.0, 4.0, 5.0])
b = np.sort(a)
b
# b is now [1., 2., 3., 4., 5.]

array([1., 2., 3., 4., 5.])

In [190]:
a = np.array([1.0, 2.0, 3.0, 4.0])
b = np.array([2.0, 2.0, 2.0, 2.0])
print(a + b)

print(a + 2)

print(a - b)

print(a - 2)



[3. 4. 5. 6.]
[3. 4. 5. 6.]
[-1.  0.  1.  2.]
[-1.  0.  1.  2.]


In [191]:
a = np.array([1.0, 2.0, 3.0, 4.0])
b = np.array([2.0, 2.0, 2.0, 2.0])
print(a * b)

print(a * 2)

print(a / b)

print(a / 2)


[2. 4. 6. 8.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]
[0.5 1.  1.5 2. ]


In [13]:

arr=np.array([[[1,2,3],[3,2,1],[4,5,6]]])
print('this is a original array\n',arr)
print('this is a reverse array')
print(arr[::-1])

this is a original array
 [[[1 2 3]
  [3 2 1]
  [4 5 6]]]
this is a reverse array
[[[1 2 3]
  [3 2 1]
  [4 5 6]]]


In [16]:
import numpy as np

# Create a sample 2D array
original_array_2d = np.array([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]])

# Reverse the 2D array along both rows and columns
reversed_array_2d = original_array_2d[:,::-1]

# Print the original and reversed 2D arrays
print("Original 2D Array:")
print(original_array_2d)

print("\nReversed 2D Array:")
print(reversed_array_2d)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed 2D Array:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [17]:
import numpy as np

# Create a sample 3D array
original_array_3d = np.array([[[1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 9]],
                               [[10, 11, 12],
                                [13, 14, 15],
                                [16, 17, 18]],
                               [[19, 20, 21],
                                [22, 23, 24],
                                [25, 26, 27]]])

# Reverse the 3D array along the third dimension (axis=2)
reversed_array_3d = original_array_3d[:, :, ::-1]

# Print the original and reversed 3D arrays
print("Original 3D Array:")
print(original_array_3d)

print("\nReversed 3D Array (Along Third Dimension):")
print(reversed_array_3d)


Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Reversed 3D Array (Along Third Dimension):
[[[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]]

 [[12 11 10]
  [15 14 13]
  [18 17 16]]

 [[21 20 19]
  [24 23 22]
  [27 26 25]]]


In [21]:
import numpy as np

# Create a sample 4D array
original_array_4d = np.random.randint(20,size=(2, 3, 4, 5))

# Reverse the 4D array along the fourth dimension (axis=3)
reversed_array_4d = original_array_4d[:, :, :, ::-1]

# Print the original and reversed 4D arrays
print("Original 4D Array:")
print(original_array_4d)

print("\nReversed 4D Array (Along Fourth Dimension):")
print(reversed_array_4d)


Original 4D Array:
[[[[ 7  9  7  8  2]
   [10 16  2  8  2]
   [ 8 18 18  9 16]
   [13  3 12 12 15]]

  [[ 5  3  2  5  1]
   [ 2  1  6 10  7]
   [16  6  2 17 12]
   [13  3 12  9 17]]

  [[11  0  1 11 19]
   [17 12 13 10 11]
   [15 14  3  4 18]
   [ 6  1  2  5  3]]]


 [[[19 15  9  0  5]
   [ 5  8  7 18  4]
   [ 1 10  9 18  6]
   [11  5  3 11  5]]

  [[17  8  6  8 11]
   [19 17  2  3  9]
   [19  4 15  5  9]
   [12 18  7  9 19]]

  [[16 16 18  2 12]
   [ 9  7 13 14  6]
   [ 0 11 16 16 14]
   [19 16  4  3  6]]]]

Reversed 4D Array (Along Fourth Dimension):
[[[[ 2  8  7  9  7]
   [ 2  8  2 16 10]
   [16  9 18 18  8]
   [15 12 12  3 13]]

  [[ 1  5  2  3  5]
   [ 7 10  6  1  2]
   [12 17  2  6 16]
   [17  9 12  3 13]]

  [[19 11  1  0 11]
   [11 10 13 12 17]
   [18  4  3 14 15]
   [ 3  5  2  1  6]]]


 [[[ 5  0  9 15 19]
   [ 4 18  7  8  5]
   [ 6 18  9 10  1]
   [ 5 11  3  5 11]]

  [[11  8  6  8 17]
   [ 9  3  2 17 19]
   [ 9  5 15  4 19]
   [19  9  7 18 12]]

  [[12  2 18 16 16]
   [ 6 14